# Generated by Django 4.2 on 2024-12-14 14:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newslettersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
