# Generated by Django 4.2 on 2024-12-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contactmessage_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('review_text', models.TextField()),
                ('reviewer_name', models.CharField(blank=True, max_length=255)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-review_date'],
            },
        ),
    ]
