# Generated by Django 4.2 on 2024-12-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitereview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitereview',
            options={},
        ),
        migrations.RenameField(
            model_name='sitereview',
            old_name='review_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='sitereview',
            name='review_text',
        ),
        migrations.RemoveField(
            model_name='sitereview',
            name='reviewer_name',
        ),
        migrations.AddField(
            model_name='sitereview',
            name='description',
            field=models.TextField(default='very good'),
        ),
        migrations.AddField(
            model_name='sitereview',
            name='image',
            field=models.ImageField(null=True, upload_to='reviews/images/'),
        ),
        migrations.AddField(
            model_name='sitereview',
            name='name',
            field=models.CharField(blank=True, default='Ahmed', max_length=255),
        ),
        migrations.AddField(
            model_name='sitereview',
            name='title',
            field=models.CharField(blank=True, default='review', max_length=255),
        ),
        migrations.AddField(
            model_name='sitereview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sitereview',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=1),
        ),
    ]
