# Generated by Django 4.2 on 2024-12-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
