# Generated by Django 4.2 on 2024-12-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='cars/images/default.jpg', upload_to='cars/images/'),
        ),
    ]
